language: objective-c
   
before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'   
     
script: 
   xctool -project Fibonacci.xcodeproj -scheme Fibonacci build -sdk iphonesimulator
